language: groovy

jdk:
- oraclejdk8

services:
- rabbitmq

install:
  - export CDIR=`pwd`
  - git clone https://github.com/olliefreeman/grails-rabbitmq-native.git ~/olliefreeman/grails-rabbitmq-native
  - git checkout v3.2.1-rabbitmq-native3
  - cd ~/olliefreeman/grails-rabbitmq-native
  - ./gradlew install
  - cd $CDIR

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/