grails:
    profile: web
    codegen:
        defaultPackage: ox.softeng.burst.grails.plugin
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false
---
rabbitmq:
    connection:
        host: 'localhost'
        username: 'guest'
        password: 'guest'
        isDefault: true
        name: 'default'
    queues:
        exchange_Carfax:
            type: topic
            durable: true
            queues:
                queue_burst:
                    durable: true
                    binding: '#.burst'
                queue_sample-tracking:
                    durable: true
                    binding: '#.sample-tracking'
        exchange_test:
            type: 'topic'
            autoDelete: false
            queues:
                queue_subset:
                    autoDelete: true
                    binding: 'test.#'
                queue_exception:
                    autoDelete: true
                    binding: 'test.exception'
                queue_validation:
                    autoDelete: true
                    binding: 'test.validation'

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE